airbnb/urls.py
from django.urls import path

from . import views

app_name = 'airbnb'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search/', views.list, name='search'),
    path('search/<query>/', views.list, name='search'),
    #path('<str:pk>/', views.DetailView.as_view(), name='detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('airbnb/', admin.site.urls),
    #path('airbnb/', include('airbnb.urls')),
]

airbnb/models.py
from django.db import models


class Location(models.Model):
    id = models.CharField(max_length=100, primary_key=True)
    listing_url = models.URLField()
    name = models.CharField(max_length=100)
    host_url = models.URLField
    host_name = models.CharField(max_length=100)
    precinct = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=5)
    latitude = models.CharField(max_length=100)
    longitude = models.CharField(max_length=100)
    price = models.CharField(max_length=100)#FloatField
    review_scores_rating = models.CharField(max_length=100)#IntegerField
    price_as_dp = models.CharField(max_length=100)#FloatField
    rating_as_int = models.CharField(max_length=100)#IntegerField
    precint = models.CharField(max_length=100)
    crime_count = models.CharField(max_length=100)#IntegerField
    precint_crime_rating = models.CharField(max_length=100)#FloatField
    goal_function = models.CharField(max_length=100)#FloatField
    
    def __str__(self):
        if self.name is not None and self.host_name is not None:
            return self.name + ", " + self.host_name
        else:
            return "could not return full name, sth was empty"
        
    def safety_mark(self):
        return self.goal_function

airbnb/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from django.views import generic

from .models import Location

import sys

class IndexView(generic.ListView):
    template_name = 'airbnb/index.html'
    context_object_name = 'couple_of_locations'
    
    def get_queryset(self):
        return Location.objects.order_by('-precint_crime_rating')[:100]
    
class DetailView(generic.DetailView):
    model = Location
    template_name = 'airbnb/detail.html'
    
#class ListView(generic.ListView):
#    model = Location
#    paginate_by = 50
#    template_name = 'airbnb/list.html'
    
#    def get_queryset(self, **kwargs):
#        print("kwargs: ")
#        print(self.kwargs, file=sys.stderr)
#        query = kwargs['query']
#        arg = query[2:]
#        return Location.objects.filter(host_name=arg)
    
    #def get_context_data(self):#, **kwargs):
    #    #query = self.request.GET.get('q')
    #    context = Location.objects.order_by('-precint_crime_rating')[:100]
    #    return context
   
def index(request):
    couple_of_locations = Location.objects.order_by('-precint_crime_rating')[:10]
    template = loader.get_template('airbnb/index.html')
    context = {
        'couple_of_locations' : couple_of_locations,
        }
    return HttpResponse(template.render(context, request))
    
def detail(request, location_id):
    try:
        location = Location.objects.get(pk=location_id)
    except Location.DoesNotExist:
        raise Http404("Location does not exist")
    return render(request, 'airbnb/detail.html', {'location': location})
    
def list(request, query):
    results = Location.objects.filter(host_name=query)
    return render(request, 'airbnb/list.html', {'results': results})

airbnb/templates/airbnb/detail.html
{{ location }}

airbnb/templates/airbnb/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'airbnb/style.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div>
	<form action="{% url 'airbnb:search' query%}" method="GET">
      <input type="text" placeholder="Search.." name="query" value="{{request.GET.query}}">
      <button type="submit"><i class="fa fa-search"></i></button>
	</form>
</div>

{% if couple_of_locations %}
    <ul>
    {% for location in couple_of_locations %}
        <li><a href="/airbnb/{{ location.id }}/">{{ location.host_name }}, {{ location.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No locations are available.</p>
{% endif %}

airbnb/templates/airbnb/list.html
{% if results %}
    <ul>
    {% for location in results %}
        <li><a href="/airbnb/{{ location.id }}/">{{ location.host_name }}, {{ location.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No search reuslts.</p>
{% endif %}